# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newreservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdb',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='reservationdb',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='reservationdb',
            old_name='time',
            new_name='Time',
        ),
    ]
